### ISSUE TITLE
IBM Watson Concept Insights get related concepts (corpus) using cURL timing out

### ISSUE THREAD

**Issue by blacknred0** [watson-developer-cloud/concept-insights-nodejs#45]
This issue is related to this link as well -> http://stackoverflow.com/questions/37326709/ibm-watson-concept-insights-get-related-concepts-corpus-using-curl-timing-out

I am getting this error -> `{"code": 500, "message": "Forwarding error"}` every time I try to get related concepts from my private account and corpus.  The error seems to be a timeout error since it always dies at 2:30.

I've replaced the sample provided by IBM to point to my account and corpus.  Does anybody know why this is occurring?

    curl -u "{username}":"{password}" "https://gateway.watsonplatform.net/concept-insights/api/v2/corpora/accountid/corpus/related_concepts?limit=3&level=0"

cURL result

      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0    44    0    44    0     0      0      0 --:--:--  0:02:30 --:--:--    10

Corpus status

    {"id":"/corpora/accountid/corpus","documents":10,"last_updated":"0001-01-01T00:00:00Z","build_status":{"ready":10,"error":0,"processing":0}}

NOTE: I do not get this error if I use the public example provided by IBM on the API.  I have also masked my account id, corpus, username, and password for this public posting.

**Comment by kognate** [comment]
This error is corpus specific, so you should create a ticket ( here is how to do that https://developer.ibm.com/bluemix/support/#support)  and then you can securely exchange your credtials with support.
